<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" href="/css/main.css" media="screen, handheld" />
    </head>
    <body>
        <h1>Artículos</h1>
        <div>Brenvita</div>

        <?php if (isset($id)) : ?>
            <h2>Artículo: <?= htmlspecialchars($id); ?>!</h2>
        <?php else: ?>
            <p>Lista de todos los artículos</a>
        <?php endif; ?>
        <?php
            var_dump($data);
        ?>
    </body>
</html>
