<?php
    if (!isset($_SESSION['user'])) {
        header('Location: /articulos');
        break;
    }
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" href="/css/main.css" media="screen, handheld" />
    </head>
    <body>
        <h1>Artículos</h1>
        <div>Brenvita</div>

        <h3>Agregar artículo</h3>
        <form method="POST" action="/articulos/new">
            <input type="text" name="title" placeholder="Título"><br>
            <input type="text" name="video" placeholder="Link al video"><br><br>
            <textarea name="text">Texto del artículo</textarea><br>
            <button>Guardar</button>
        </form>
    </body>
</html>
